 server:
  port: 8080
 spring:
  elasticsearch:
    uris: http://localhost:9200
  datasource:
     username: root
     password: 123456
     url: jdbc:mysql:///springbootdemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
     driver-class-name: com.mysql.cj.jdbc.Driver
     type: com.alibaba.druid.pool.DruidDataSource
  mybatis:
     type-aliases-package: org.sherlock.User" #别名
     mapper-locations: classpath:mapper/*.xml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-idle: 16
        max-active: 32
        min-idle: 8

 del:
   file:
     quartz:
       cron: "0/5 * * * * ?" # 每小时执行一次

 restTemplate:
   post:
     url: "http://119.23.80.65/jscp-api/jscp-new-visit/mobileVisit/submitBookOrInviteInfo"
 test:
   testValue: "qwer1234"
   url: "http://127.0.0.1:8080/springBoot/test"